version: "3.7"

services:
  api:
    build: .
    container_name: go-mux-api
    image: github.com/atkinsonbg/go-gmux-proper-unit-testing/api:latest
    environment:
      CONNECTION_STRING: host=go-mux-db dbname=go-mux-db user=postgres
      DATABASE_URL: postgresql://postgres@go-mux-db:5432/go-mux-db
    ports:
      - 80:80

  database:
    container_name: go-mux-db
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: go-mux-db
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432